name: SolidState
favicon: null
layout_spectrum: 0.45234
typography_spectrum: 0.76
title: 'Computer Repair & Support for Haliburton '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#242424'
    - '#fcff00'
    - '#ffffff'
    - '#f75800'
    - '#ffa200'
  brandStrength: 0.6875
  lightness: 0.07698837528005242
  saturation: 0.12521754251793027
  rhythmicContrast: 0.5
purpose: []
